version: '3.3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - php
      - mariadb 
    networks:
      - laravel

  mariadb:
      image: mariadb:latest
      container_name: mariadb
      restart: always
      ports:
       - "4306:3306"
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        MARIADB_DATABASE: cache
        MARIADB_USER: homestead
        MARIADB_PASSWORD: secret
        MARIADB_ROOT_PASSWORD: secret
      networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src/:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel
  
  redis:
    image: redis:7.4.1-alpine
    restart: always
    container_name: redis
    volumes:
      - /redis:/root/redis
    ports:
      - "6479:6379"
    environment:
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - laravel